# Generated by Django 3.2.8 on 2021-11-12 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('comp_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=20)),
                ('date_inco', models.DateField()),
                ('interest', models.TextField()),
                ('about', models.TextField()),
                ('logo', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='FollowerPersonal',
            fields=[
                ('follower_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=40)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'db_table': 'follower_personal',
            },
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Authentication.company')),
                ('contact_email', models.CharField(max_length=40)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=60, null=True)),
                ('reach', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'company_contact',
            },
        ),
        migrations.CreateModel(
            name='FollowerProf',
            fields=[
                ('follower', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Authentication.followerpersonal')),
                ('header', models.CharField(blank=True, max_length=80, null=True)),
                ('interests', models.TextField(blank=True, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('git_website', models.CharField(blank=True, max_length=40, null=True)),
                ('work_exp', models.TextField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, default=None, max_length=150, null=True)),
            ],
            options={
                'db_table': 'follower_prof',
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('job_id', models.IntegerField(primary_key=True, serialize=False)),
                ('job_date', models.DateField()),
                ('job_title', models.CharField(max_length=40)),
                ('job_desc', models.TextField()),
                ('jd_pdf', models.CharField(blank=True, max_length=150, null=True)),
                ('job_type', models.CharField(blank=True, max_length=30, null=True)),
                ('job_location', models.CharField(blank=True, max_length=50, null=True)),
                ('link', models.CharField(blank=True, max_length=70, null=True)),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Authentication.company')),
            ],
            options={
                'db_table': 'job_post',
            },
        ),
    ]
