# Generated by Django 3.2.8 on 2021-11-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('comp_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=20)),
                ('date_inco', models.DateField()),
                ('interest', models.TextField()),
                ('about', models.TextField()),
                ('logo', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.CharField(max_length=40)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=60, null=True)),
                ('reach', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'company_contact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FollowerPersonal',
            fields=[
                ('follower_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=40)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'db_table': 'follower_personal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FollowerProf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=80, null=True)),
                ('interests', models.TextField(blank=True, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('git_website', models.CharField(blank=True, max_length=40, null=True)),
                ('work_exp', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': 'follower_prof',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('job_id', models.IntegerField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=40)),
                ('job_desc', models.TextField()),
                ('jd_pdf', models.FileField(blank=True, null=True, upload_to='')),
                ('job_type', models.CharField(blank=True, max_length=30, null=True)),
                ('job_location', models.CharField(blank=True, max_length=50, null=True)),
                ('link', models.CharField(blank=True, max_length=70, null=True)),
            ],
            options={
                'db_table': 'job_post',
                'managed': False,
            },
        ),
    ]
